version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "sneeom"
github_repo = "take11"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev-take.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::206572126289:role/aws-sam-cli-managed-dev-take--PipelineExecutionRole-suIMUvpXGFmy"
cloudformation_execution_role = "arn:aws:iam::206572126289:role/aws-sam-cli-managed-dev-t-CloudFormationExecutionRo-OfWHVZtPwhwW"
artifacts_bucket = "aws-sam-cli-managed-dev-take-pipel-artifactsbucket-5b1dln1dipc8"
image_repository = ""
region = "us-east-1"

[prod-take11.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::206572126289:role/aws-sam-cli-managed-prod-take-PipelineExecutionRole-GLrmiHn5sgve"
cloudformation_execution_role = "arn:aws:iam::206572126289:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-6yaXAz62l1uQ"
artifacts_bucket = "aws-sam-cli-managed-prod-take11-pi-artifactsbucket-z1rt6vrt2fau"
image_repository = ""
region = "us-west-2"
